-- =============================================================================
-- Migración 0015: "Internacional" para colombianos en el exterior
-- Se registra como un departamento más (código EX) y sus "municipios" son los países.
-- =============================================================================

insert into public.departamentos (id, nombre, slug, region)
values ('EX', 'Internacional (colombianos en el exterior)', 'internacional', 'Exterior')
on conflict (id) do update set nombre = excluded.nombre, slug = excluded.slug, region = excluded.region;

insert into public.municipios (id, departamento_id, nombre, slug, es_capital) values
  ('EX-AD', 'EX', 'Andorra', 'andorra', false),
  ('EX-AE', 'EX', 'Emiratos Árabes Unidos', 'emiratos-arabes-unidos', false),
  ('EX-AF', 'EX', 'Afganistán', 'afganistan', false),
  ('EX-AG', 'EX', 'Antigua y Barbuda', 'antigua-y-barbuda', false),
  ('EX-AL', 'EX', 'Albania', 'albania', false),
  ('EX-AM', 'EX', 'Armenia', 'armenia', false),
  ('EX-AO', 'EX', 'Angola', 'angola', false),
  ('EX-AR', 'EX', 'Argentina', 'argentina', false),
  ('EX-AT', 'EX', 'Austria', 'austria', false),
  ('EX-AU', 'EX', 'Australia', 'australia', false),
  ('EX-AZ', 'EX', 'Azerbaiyán', 'azerbaiyan', false),
  ('EX-BA', 'EX', 'Bosnia y Herzegovina', 'bosnia-y-herzegovina', false),
  ('EX-BB', 'EX', 'Barbados', 'barbados', false),
  ('EX-BD', 'EX', 'Bangladés', 'banglades', false),
  ('EX-BE', 'EX', 'Bélgica', 'belgica', false),
  ('EX-BF', 'EX', 'Burkina Faso', 'burkina-faso', false),
  ('EX-BG', 'EX', 'Bulgaria', 'bulgaria', false),
  ('EX-BH', 'EX', 'Baréin', 'barein', false),
  ('EX-BI', 'EX', 'Burundi', 'burundi', false),
  ('EX-BJ', 'EX', 'Benín', 'benin', false),
  ('EX-BN', 'EX', 'Brunéi', 'brunei', false),
  ('EX-BO', 'EX', 'Bolivia', 'bolivia', false),
  ('EX-BR', 'EX', 'Brasil', 'brasil', false),
  ('EX-BS', 'EX', 'Bahamas', 'bahamas', false),
  ('EX-BT', 'EX', 'Bután', 'butan', false),
  ('EX-BW', 'EX', 'Botsuana', 'botsuana', false),
  ('EX-BY', 'EX', 'Bielorrusia', 'bielorrusia', false),
  ('EX-BZ', 'EX', 'Belice', 'belice', false),
  ('EX-CA', 'EX', 'Canadá', 'canada', false),
  ('EX-CD', 'EX', 'República Democrática del Congo', 'republica-democratica-del-congo', false),
  ('EX-CF', 'EX', 'República Centroafricana', 'republica-centroafricana', false),
  ('EX-CG', 'EX', 'Congo', 'congo', false),
  ('EX-CH', 'EX', 'Suiza', 'suiza', false),
  ('EX-CI', 'EX', 'Côte d’Ivoire', 'cote-d-ivoire', false),
  ('EX-CL', 'EX', 'Chile', 'chile', false),
  ('EX-CM', 'EX', 'Camerún', 'camerun', false),
  ('EX-CN', 'EX', 'China', 'china', false),
  ('EX-CR', 'EX', 'Costa Rica', 'costa-rica', false),
  ('EX-CU', 'EX', 'Cuba', 'cuba', false),
  ('EX-CV', 'EX', 'Cabo Verde', 'cabo-verde', false),
  ('EX-CY', 'EX', 'Chipre', 'chipre', false),
  ('EX-CZ', 'EX', 'Chequia', 'chequia', false),
  ('EX-DE', 'EX', 'Alemania', 'alemania', false),
  ('EX-DJ', 'EX', 'Yibuti', 'yibuti', false),
  ('EX-DK', 'EX', 'Dinamarca', 'dinamarca', false),
  ('EX-DM', 'EX', 'Dominica', 'dominica', false),
  ('EX-DO', 'EX', 'República Dominicana', 'republica-dominicana', false),
  ('EX-DZ', 'EX', 'Argelia', 'argelia', false),
  ('EX-EC', 'EX', 'Ecuador', 'ecuador', false),
  ('EX-EE', 'EX', 'Estonia', 'estonia', false),
  ('EX-EG', 'EX', 'Egipto', 'egipto', false),
  ('EX-ER', 'EX', 'Eritrea', 'eritrea', false),
  ('EX-ES', 'EX', 'España', 'espana', false),
  ('EX-ET', 'EX', 'Etiopía', 'etiopia', false),
  ('EX-FI', 'EX', 'Finlandia', 'finlandia', false),
  ('EX-FJ', 'EX', 'Fiyi', 'fiyi', false),
  ('EX-FM', 'EX', 'Micronesia', 'micronesia', false),
  ('EX-FR', 'EX', 'Francia', 'francia', false),
  ('EX-GA', 'EX', 'Gabón', 'gabon', false),
  ('EX-GB', 'EX', 'Reino Unido', 'reino-unido', false),
  ('EX-GD', 'EX', 'Granada', 'granada', false),
  ('EX-GE', 'EX', 'Georgia', 'georgia', false),
  ('EX-GH', 'EX', 'Ghana', 'ghana', false),
  ('EX-GM', 'EX', 'Gambia', 'gambia', false),
  ('EX-GN', 'EX', 'Guinea', 'guinea', false),
  ('EX-GQ', 'EX', 'Guinea Ecuatorial', 'guinea-ecuatorial', false),
  ('EX-GR', 'EX', 'Grecia', 'grecia', false),
  ('EX-GT', 'EX', 'Guatemala', 'guatemala', false),
  ('EX-GW', 'EX', 'Guinea-Bisáu', 'guinea-bisau', false),
  ('EX-GY', 'EX', 'Guyana', 'guyana', false),
  ('EX-HN', 'EX', 'Honduras', 'honduras', false),
  ('EX-HR', 'EX', 'Croacia', 'croacia', false),
  ('EX-HT', 'EX', 'Haití', 'haiti', false),
  ('EX-HU', 'EX', 'Hungría', 'hungria', false),
  ('EX-ID', 'EX', 'Indonesia', 'indonesia', false),
  ('EX-IE', 'EX', 'Irlanda', 'irlanda', false),
  ('EX-IL', 'EX', 'Israel', 'israel', false),
  ('EX-IN', 'EX', 'India', 'india', false),
  ('EX-IQ', 'EX', 'Irak', 'irak', false),
  ('EX-IR', 'EX', 'Irán', 'iran', false),
  ('EX-IS', 'EX', 'Islandia', 'islandia', false),
  ('EX-IT', 'EX', 'Italia', 'italia', false),
  ('EX-JM', 'EX', 'Jamaica', 'jamaica', false),
  ('EX-JO', 'EX', 'Jordania', 'jordania', false),
  ('EX-JP', 'EX', 'Japón', 'japon', false),
  ('EX-KE', 'EX', 'Kenia', 'kenia', false),
  ('EX-KG', 'EX', 'Kirguistán', 'kirguistan', false),
  ('EX-KH', 'EX', 'Camboya', 'camboya', false),
  ('EX-KI', 'EX', 'Kiribati', 'kiribati', false),
  ('EX-KM', 'EX', 'Comoras', 'comoras', false),
  ('EX-KN', 'EX', 'San Cristóbal y Nieves', 'san-cristobal-y-nieves', false),
  ('EX-KP', 'EX', 'Corea del Norte', 'corea-del-norte', false),
  ('EX-KR', 'EX', 'Corea del Sur', 'corea-del-sur', false),
  ('EX-KW', 'EX', 'Kuwait', 'kuwait', false),
  ('EX-KZ', 'EX', 'Kazajistán', 'kazajistan', false),
  ('EX-LA', 'EX', 'Laos', 'laos', false),
  ('EX-LB', 'EX', 'Líbano', 'libano', false),
  ('EX-LC', 'EX', 'Santa Lucía', 'santa-lucia', false),
  ('EX-LI', 'EX', 'Liechtenstein', 'liechtenstein', false),
  ('EX-LK', 'EX', 'Sri Lanka', 'sri-lanka', false),
  ('EX-LR', 'EX', 'Liberia', 'liberia', false),
  ('EX-LS', 'EX', 'Lesoto', 'lesoto', false),
  ('EX-LT', 'EX', 'Lituania', 'lituania', false),
  ('EX-LU', 'EX', 'Luxemburgo', 'luxemburgo', false),
  ('EX-LV', 'EX', 'Letonia', 'letonia', false),
  ('EX-LY', 'EX', 'Libia', 'libia', false),
  ('EX-MA', 'EX', 'Marruecos', 'marruecos', false),
  ('EX-MC', 'EX', 'Mónaco', 'monaco', false),
  ('EX-MD', 'EX', 'Moldavia', 'moldavia', false),
  ('EX-ME', 'EX', 'Montenegro', 'montenegro', false),
  ('EX-MG', 'EX', 'Madagascar', 'madagascar', false),
  ('EX-MH', 'EX', 'Islas Marshall', 'islas-marshall', false),
  ('EX-MK', 'EX', 'Macedonia del Norte', 'macedonia-del-norte', false),
  ('EX-ML', 'EX', 'Mali', 'mali', false),
  ('EX-MM', 'EX', 'Myanmar (Birmania)', 'myanmar-birmania', false),
  ('EX-MN', 'EX', 'Mongolia', 'mongolia', false),
  ('EX-MR', 'EX', 'Mauritania', 'mauritania', false),
  ('EX-MT', 'EX', 'Malta', 'malta', false),
  ('EX-MU', 'EX', 'Mauricio', 'mauricio', false),
  ('EX-MV', 'EX', 'Maldivas', 'maldivas', false),
  ('EX-MW', 'EX', 'Malaui', 'malaui', false),
  ('EX-MX', 'EX', 'México', 'mexico', false),
  ('EX-MY', 'EX', 'Malasia', 'malasia', false),
  ('EX-MZ', 'EX', 'Mozambique', 'mozambique', false),
  ('EX-NA', 'EX', 'Namibia', 'namibia', false),
  ('EX-NE', 'EX', 'Níger', 'niger', false),
  ('EX-NG', 'EX', 'Nigeria', 'nigeria', false),
  ('EX-NI', 'EX', 'Nicaragua', 'nicaragua', false),
  ('EX-NL', 'EX', 'Países Bajos', 'paises-bajos', false),
  ('EX-NO', 'EX', 'Noruega', 'noruega', false),
  ('EX-NP', 'EX', 'Nepal', 'nepal', false),
  ('EX-NR', 'EX', 'Nauru', 'nauru', false),
  ('EX-NZ', 'EX', 'Nueva Zelanda', 'nueva-zelanda', false),
  ('EX-OM', 'EX', 'Omán', 'oman', false),
  ('EX-PA', 'EX', 'Panamá', 'panama', false),
  ('EX-PE', 'EX', 'Perú', 'peru', false),
  ('EX-PG', 'EX', 'Papúa Nueva Guinea', 'papua-nueva-guinea', false),
  ('EX-PH', 'EX', 'Filipinas', 'filipinas', false),
  ('EX-PK', 'EX', 'Pakistán', 'pakistan', false),
  ('EX-PL', 'EX', 'Polonia', 'polonia', false),
  ('EX-PS', 'EX', 'Territorios Palestinos', 'territorios-palestinos', false),
  ('EX-PT', 'EX', 'Portugal', 'portugal', false),
  ('EX-PW', 'EX', 'Palaos', 'palaos', false),
  ('EX-PY', 'EX', 'Paraguay', 'paraguay', false),
  ('EX-QA', 'EX', 'Catar', 'catar', false),
  ('EX-RO', 'EX', 'Rumanía', 'rumania', false),
  ('EX-RS', 'EX', 'Serbia', 'serbia', false),
  ('EX-RU', 'EX', 'Rusia', 'rusia', false),
  ('EX-RW', 'EX', 'Ruanda', 'ruanda', false),
  ('EX-SA', 'EX', 'Arabia Saudí', 'arabia-saudi', false),
  ('EX-SB', 'EX', 'Islas Salomón', 'islas-salomon', false),
  ('EX-SC', 'EX', 'Seychelles', 'seychelles', false),
  ('EX-SD', 'EX', 'Sudán', 'sudan', false),
  ('EX-SE', 'EX', 'Suecia', 'suecia', false),
  ('EX-SG', 'EX', 'Singapur', 'singapur', false),
  ('EX-SI', 'EX', 'Eslovenia', 'eslovenia', false),
  ('EX-SK', 'EX', 'Eslovaquia', 'eslovaquia', false),
  ('EX-SL', 'EX', 'Sierra Leona', 'sierra-leona', false),
  ('EX-SM', 'EX', 'San Marino', 'san-marino', false),
  ('EX-SN', 'EX', 'Senegal', 'senegal', false),
  ('EX-SO', 'EX', 'Somalia', 'somalia', false),
  ('EX-SR', 'EX', 'Surinam', 'surinam', false),
  ('EX-SS', 'EX', 'Sudán del Sur', 'sudan-del-sur', false),
  ('EX-ST', 'EX', 'Santo Tomé y Príncipe', 'santo-tome-y-principe', false),
  ('EX-SV', 'EX', 'El Salvador', 'el-salvador', false),
  ('EX-SY', 'EX', 'Siria', 'siria', false),
  ('EX-SZ', 'EX', 'Esuatini', 'esuatini', false),
  ('EX-TD', 'EX', 'Chad', 'chad', false),
  ('EX-TG', 'EX', 'Togo', 'togo', false),
  ('EX-TH', 'EX', 'Tailandia', 'tailandia', false),
  ('EX-TJ', 'EX', 'Tayikistán', 'tayikistan', false),
  ('EX-TL', 'EX', 'Timor-Leste', 'timor-leste', false),
  ('EX-TM', 'EX', 'Turkmenistán', 'turkmenistan', false),
  ('EX-TN', 'EX', 'Túnez', 'tunez', false),
  ('EX-TO', 'EX', 'Tonga', 'tonga', false),
  ('EX-TR', 'EX', 'Turquía', 'turquia', false),
  ('EX-TT', 'EX', 'Trinidad y Tobago', 'trinidad-y-tobago', false),
  ('EX-TV', 'EX', 'Tuvalu', 'tuvalu', false),
  ('EX-TZ', 'EX', 'Tanzania', 'tanzania', false),
  ('EX-UA', 'EX', 'Ucrania', 'ucrania', false),
  ('EX-UG', 'EX', 'Uganda', 'uganda', false),
  ('EX-US', 'EX', 'Estados Unidos', 'estados-unidos', false),
  ('EX-UY', 'EX', 'Uruguay', 'uruguay', false),
  ('EX-UZ', 'EX', 'Uzbekistán', 'uzbekistan', false),
  ('EX-VA', 'EX', 'Ciudad del Vaticano', 'ciudad-del-vaticano', false),
  ('EX-VC', 'EX', 'San Vicente y las Granadinas', 'san-vicente-y-las-granadinas', false),
  ('EX-VE', 'EX', 'Venezuela', 'venezuela', false),
  ('EX-VN', 'EX', 'Vietnam', 'vietnam', false),
  ('EX-VU', 'EX', 'Vanuatu', 'vanuatu', false),
  ('EX-WS', 'EX', 'Samoa', 'samoa', false),
  ('EX-YE', 'EX', 'Yemen', 'yemen', false),
  ('EX-ZA', 'EX', 'Sudáfrica', 'sudafrica', false),
  ('EX-ZM', 'EX', 'Zambia', 'zambia', false),
  ('EX-ZW', 'EX', 'Zimbabue', 'zimbabue', false),
  ('EX-PR', 'EX', 'Puerto Rico', 'puerto-rico', false),
  ('EX-AW', 'EX', 'Aruba', 'aruba', false),
  ('EX-CW', 'EX', 'Curazao', 'curazao', false)
on conflict (id) do update set nombre = excluded.nombre, slug = excluded.slug;

-- El grupo Internacional queda asociado al nuevo "departamento"
update public.grupos_whatsapp set departamento_id = 'EX', departamento_moderacion = 'EX'
where url = 'https://chat.whatsapp.com/Hx82zqfGfpTKrE7wwTDd7J';
